# Generated by Django 2.0.2 on 2018-02-05 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=100)),
                ('eventName', models.CharField(max_length=50)),
                ('date_time', models.CharField(max_length=50)),
                ('durarion', models.CharField(max_length=20)),
                ('venue', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('imageReference1', models.CharField(max_length=1000)),
                ('imageReference2', models.CharField(max_length=1000)),
                ('imageReference3', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiyq.Event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('imageReference1', models.CharField(max_length=1000)),
                ('imageReference2', models.CharField(max_length=1000)),
                ('imageReference3', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=250)),
                ('sexualPreference', models.CharField(max_length=250)),
                ('premium', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='U1', to='hiyq.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='U2', to='hiyq.User'),
        ),
    ]
